
(in-package :abstractnode.compiler)

(defgeneric compile-requirements (backend-indicator)
  (:documentation
   "## [generic] compile-requirements

```
(compile-requirements backend-indicator)
```

This method is a one of compile-components inserting the string this method returned when compiling. It could be userful for writing requirements at the top of codes as the name implies;

```clang
#include <omp.h>   }
#include <sleef.h> } Generated by the compile-requirements method
     ...           }

// Your Code Follows
```

If the method is unnecessary for the certain backend, users can simply return \"\" being ignored.
"))

(defmethod compile-requirements ((backend-indicator t))
  (error
   'Backend-Missing-Operation
   :op-type "compile-requirements"
   :backend backend-indicator))

